print("Enter the first number :")
num1 = input()
print("Enter the second number :")
num2 = input()
# print("Sum of num1 and num2 is :", int(num1) + int(num2))
print("sum of num1 and num2 is :", int(num1 + num2))
print(type(int(num1 + num2)))